import { reactive } from 'vue'
export const store = reactive({
    login: false,
    isAdmin: false,
    loginDialogAppear: false,
    header: {
        'accept': 'application/json',
        accessToken: '',
        tokenType: '',
        'Authorization': 'this is dev authorization',
    },
    user: {
        id: 1,
        username: 'bubble',
        stu_id: '',
        phone: '',
        email: '',
        image_url: 'https://img0.baidu.com/it/u=962511916,1823173324&fm=253&fmt=auto&app=120&f=JPEG?w=501&h=500' ,
        created_at: null,
        updated_at: null,
    },
    keyword:{
        id: 0,
        keyword: "",
        heat: 0,
        sentiment: 0.0,
        createTime: "2024-10-29 22:48:42",
        updateTime: "2024-10-29 22:48:42",
        analysis: "",
        representativeEvent:{},
    },
    event:{
        id: 0,
        keywordId: 0,
        description: "",
        newsIds: "",
        heat: 0,
        sentiment: 0.0,
        urls: "",
        eventDatetime: "2024-10-29 22:48:42",
        createTime: "2024-10-29 22:48:42",
        updateTime: "2024-10-29 22:48:42",
    },
    news:{
        id: 0,
        source: "",
        title: "",
        author: "",
        content: "",
        heat: "",
        publishDatetime: "2024-10-29 22:48:42",
        url: "",
    },
    homePageParams:{
        filter:{
            searchTerm: '',
        },
    },
    sentimentValue: 0,
})